[project]
name = "tabela"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "holidays>=0.86",
    "pandas>=2.3.3",
    "st-gsheets-connection>=0.1.0",
    "streamlit>=1.28",
]
